name: Test v2ray configs json format

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  configs-check:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        configs: [
          "v2ray-relay-server",
          "v2ray-upstream-server",
          "v2ray-caddy-cdn",
          "v2ray-nginx-cdn"
        ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: check json configs format
        run: npm install jsonlint -g > '/dev/null' 2>&1 && jsonlint ./${{ matrix.configs }}/v2ray.json
